### ISSUE TITLE
Incompatibility since Home Assistant Core 2025.12 (ImportError: POWER_VOLT_AMPERE_REACTIVE)

### ISSUE THREAD

**Issue by Houskad** [mletenay/home-assistant-goodwe-inverter#402]
Hi,

Would somebody help me with this please? I am a bit more advanced user, not a programmer unfortunately....

After upgrading Home Assistant Core from 2025.11 to 2026.1 (and previously also to 2025.12) the GoodWe custom integration no longer loads.

Error in logs:
ImportError: cannot import name 'POWER_VOLT_AMPERE_REACTIVE'
from 'homeassistant.const'

Stacktrace points to:
/config/custom_components/goodwe/sensor.py

The integration worked correctly on HA Core 2025.11. It seems the error is related to changes in HA 2025.12 / 2026.1 / Python 3.13. Downgrading back to HA 2025.11 restores full functionality, so I downgraded and I am on 2025.11 now.

I use the integration not only for monitoring but also for controlling the inverter / battery / EV charging, so compatibility with newer HA versions is important for me. I cannot use standard HA integration.

Could you please let me know if there is a fix I can make? Or if you work on solution and new version?

Thank you very much for your work on this integration.

David

Full log message:

Detaily logování (CHYBA)  ImportError: cannot import name 'POWER_VOLT_AMPERE_REACTIVE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.pyor setting up entry GoodWe for goodwe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/goodwe/__init__.py", line 75, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2611, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1188, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1188, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1188, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/goodwe/sensor.py", line 20, in <module>
    from homeassistant.const import (
    ...<11 lines>...
    )
ImportError: cannot import name 'POWER_VOLT_AMPERE_REACTIVE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
